# Generated by Django 5.0.1 on 2024-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:15 - 12:15', '11:15 - 12:15'), ('12:15 - 13:15', '12:15 - 13:15'), ('13:45 - 14:45', '13:45 - 14:45'), ('14:45 - 15:45', '14:45 - 15:45'), ('15:45 - 16:45', '15:45 - 16:45')], default='11:30 - 12:30', max_length=50),
        ),
    ]
